services:
  script:
    container_name: SCRIPT
    command: python -m script.main
    build: 
      dockerfile: Dockerfile
      context: "."
    depends_on:
      - db
  db:
    container_name: DB
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./config/init-schema.sql:/docker-entrypoint-initdb.d/10-init-schema.sql
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: